apiVersion: v1
kind: Pod
metadata:
  name: estatic-web
  labels:
    name: edc
spec:
  containers:
  - name: web
    image: nginx
    ports:
      - name: webports
        containerPort: 80
        protocol: TCP
